# Generated by Django 3.2.8 on 2021-10-18 17:58

import colorfield.fields
from django.db import migrations, models


# css_header_menu_color and css_module_menu_enabled are also added by
# 0033_theme_menu_fields on the parallel branch. Use IF NOT EXISTS to
# avoid DuplicateColumn errors regardless of migration execution order.


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0022_add_logo_max_width_and_height'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='theme',
                    name='css_header_menu_color',
                    field=colorfield.fields.ColorField(
                        blank=True,
                        default='#0C4B33',
                        help_text='#0C4B33',
                        max_length=10,
                        verbose_name='menu color',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE admin_interface_theme ADD COLUMN IF NOT EXISTS css_header_menu_color varchar(10) DEFAULT '#0C4B33' NOT NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='theme',
                    name='css_module_menu_enabled',
                    field=models.BooleanField(default=True, verbose_name='show menu'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE admin_interface_theme ADD COLUMN IF NOT EXISTS css_module_menu_enabled boolean DEFAULT true NOT NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
