# Generated by Django 3.2.8 on 2021-10-18 17:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0022_add_logo_max_width_and_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_color',
            field=colorfield.fields.ColorField(blank=True, default='#0C4B33', help_text='#0C4B33', max_length=10, verbose_name='menu color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_module_menu_enabled',
            field=models.BooleanField(default=True, verbose_name='show menu'),
        ),
    ]
