# Generated by Django 3.2.8 on 2021-10-18 17:58

import colorfield.fields
from django.db import migrations, models

from admin_interface.migration_operations import AddFieldIfNotExists

# css_header_menu_color and css_module_menu_enabled are also added by
# 0033_theme_menu_fields on the parallel branch. AddFieldIfNotExists skips
# the database change when the column is already present, regardless of
# migration execution order, and works on every backend.


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0022_add_logo_max_width_and_height'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='theme',
            name='css_header_menu_color',
            field=colorfield.fields.ColorField(
                blank=True,
                default='#0C4B33',
                help_text='#0C4B33',
                max_length=10,
                verbose_name='menu color',
            ),
        ),
        AddFieldIfNotExists(
            model_name='theme',
            name='css_module_menu_enabled',
            field=models.BooleanField(default=True, verbose_name='show menu'),
        ),
    ]
