# Generated by Django 3.2.8 on 2021-10-17 21:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0022_add_logo_max_width_and_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#0C4B33', help_text='#0C4B33', max_length=10, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_link_color',
            field=colorfield.fields.ColorField(blank=True, default='#44B78B', help_text='#44B78B', max_length=10, verbose_name='link color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_link_hover_bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#156641', help_text='#156641', max_length=10, verbose_name='link hover background color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_link_hover_color',
            field=colorfield.fields.ColorField(blank=True, default='#C9F0DD', help_text='#C9F0DD', max_length=10, verbose_name='link hover color'),
        ),
    ]
