# Generated by Django 3.2.8 on 2021-10-18 19:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0023_auto_20211018_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_header_menu_accent_color',
            field=colorfield.fields.ColorField(blank=True, default='#0C3C26', help_text='#0C3C26', max_length=10, verbose_name='menu accent color'),
        ),
    ]
