# Generated by Django 3.2.8 on 2021-10-18 21:15

import colorfield.fields
from django.db import migrations

from admin_interface.migration_operations import AddFieldIfNotExists

# css_header_menu_accent_color is also added by 0033_theme_menu_fields on the
# parallel branch. AddFieldIfNotExists skips the database change when the
# column is already present, on every backend.


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0023_auto_20211018_2058'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='theme',
            name='css_header_menu_accent_color',
            field=colorfield.fields.ColorField(
                blank=True,
                default='#0C3C26',
                help_text='#0C3C26',
                max_length=10,
                verbose_name='menu accent color',
            ),
        ),
    ]
