# Generated by Django 4.2.4 on 2023-08-17 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_interface", "0024_theme_css_header_menu_accent_color"),
        ("admin_interface", "0030_theme_collapsible_stacked_inlines_and_more"),
    ]

    operations = []
