# Generated by Django 3.2.19 on 2026-03-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0024_theme_css_header_menu_accent_color'),
        ('admin_interface', '0033_theme_menu_fields'),
    ]

    operations = [
    ]
