# Generated by Django 6.0.3 on 2026-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0035_theme_list_filter_collapsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css_module_menu_enabled',
            field=models.BooleanField(default=True, verbose_name='menu enabled'),
        ),
    ]
